apiVersion : apps/v1
kind: Deployment
metadata:
  name: azurepipelineaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurepipelineaks
  template:
    metadata:
      labels:
        app: azurepipelineaks 
    spec:
      containers:
        - name: azurepipelineaks 
          image: mycontainerregistry110619731200.azurecr.io/azurepipelineaks
          ports:
          - containerPort: 8080